apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: etl
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS etl_data (
      id SERIAL PRIMARY KEY,
      name TEXT,
      value NUMERIC,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
